### ISSUE TITLE
Graphics changes for version 1.0

### ISSUE THREAD

**Issue by Evzenecek** [ra100/shoutbox-widget#22]
Discuss with Wave

- [ ] progress wheel
- [ ] hover effect for social network type icons
- [ ] hover effect for admin badge
- [x] delete default post icon (grey R)

**Comment by ra100** [comment]
Aky je tu progress? Nevidel som ziadne vysledky k comukolvek z tychto veci.

**Comment by Evzenecek** [comment]
Asi bych to zatím neřešil.
Jen se zeptám Aleše, co si myslí o tom progress wheel...
