### ISSUE TITLE
Refresh po registraci sociální sítí

### ISSUE THREAD

**Issue by Evzenecek** [ra100/shoutbox-widget#32]
Po registraci (možná i loginu) skrze sociální síť je třeba provést refresh widgetu, aby byl uživatel přihlášen. Dokud nedojde k refreshi, přihlášení se neprojeví.

**Comment by ra100** [comment]
Aky browser?

**Comment by Evzenecek** [comment]
Teď u loginu mi to na Chrome funguje korektně. Stalo se mi to u registrace, také na Chrome.

**Comment by ra100** [comment]
Zmazal som tvoj ucet a spravil som nejake zmeny. Skus, ci to zas spravi. Mne to preslo teraz OK.

**Comment by Evzenecek** [comment]
Zkoušel jsem a taky teď OK.
