### ISSUE TITLE
Pop-up po vložení příspěvku

### ISSUE THREAD

**Issue by Evzenecek** [ra100/shoutbox-widget#33]
Nyní prázdný.
Je třeba rolišovat 2 stavy: 1) Shoutbox je moderovaný a příspěvek nejprve musí být schválen 2) Shoutbox není moderovaný a příspěvek bude ihned vidět.

1) V popupu by měla být hláška ve stylu "Vzkaz byl přidán a nyní čeká na schválení."

2) V pop-upu by měla být hláška ve stylu "Vzkaz byl přidán!"
Zároveň by pod pop-upem měl proběhnout refresh příspěvků, aby byl vložený příspěvek ihned vidět.

**Comment by ra100** [comment]
![cace3a5a-a98b-4a99-8c90-0ba25593a327](https://cloud.githubusercontent.com/assets/3185410/24065737/9eb97abc-0b6d-11e7-93bb-8460a9b3a45e.png)
