### ISSUE TITLE
Expanze widgetu

### ISSUE THREAD

**Issue by Evzenecek** [ra100/shoutbox-widget#34]
Při rozšíření widgetu pomocí tlačítka expanze proběhne na opačnou stranu - správně má být doprava.

**Comment by ra100** [comment]
Expand je designované pre použitie v pravom stĺpci a preto sa expanduje doľava. Ak to neplatí, please confirm.

**Comment by Evzenecek** [comment]
Well... Pro každou stanici může být použitý na jiné straně, měli bychom s tím počítat...
Na Wavu (první použití) s ním počítáme do leva, takže OK.

**Comment by Evzenecek** [comment]
+ také musíme počítat s mobilní verzí shoutboxu, který by neměl být rozšiřitelný.

**Comment by ra100** [comment]
Konfigurovatelne cez css, alebo classou left/right
