### ISSUE TITLE
Pop-up "Přidat vzkaz" nemá button

### ISSUE THREAD

**Issue by Evzenecek** [ra100/shoutbox-widget#35]
Je třeba doprava pod textové pole vložit button "Odeslat".

**Comment by ra100** [comment]
Well, má to button, ale najskôr tam treba niečo napísať. Ale minimálne musí byť disabled pred vyplnením textu.

**Comment by Evzenecek** [comment]
Nechal bych ho tam celou dobu. Před započtením psaní bych ho jen nechal disabled, šedý.

**Comment by ra100** [comment]
disabled transparentny, neklikatelny
