### ISSUE TITLE
Nová grafika - svg

### ISSUE THREAD

**Issue by Evzenecek** [ra100/shoutbox-widget#36]
Aleš posílá nové a upravené ikonky.
Použití v celých náhledech nahraju obratem.

[Archive.zip](https://github.com/ra100/shoutbox-widget/files/834382/Archive.zip)

![paleta_rgb_e7](https://cloud.githubusercontent.com/assets/24651120/23801694/5ad2aa88-05b1-11e7-93b9-7474ab876cc7.png)

**Comment by ra100** [comment]
v grafike este chyba, ako by mal vyzerat widget pre admina

**Comment by Evzenecek** [comment]
Sorry, přikládám.
Admin UI se spouští klikem na "edit"
Příspěvek čekající na moderaci má rámeček žlutý a ikonku nad sebou, skrytý je zesvětlený a má ikonku přeskrtlého oka.

![vzkazy_edit-mode](https://cloud.githubusercontent.com/assets/24651120/23860607/ba77f7ba-0807-11e7-8067-41bf2d37534b.jpg)
![vzkazy_redakcni-rozhrani](https://cloud.githubusercontent.com/assets/24651120/23860609/ba7bab8a-0807-11e7-85de-a97457c9f913.jpg)
![vzkazy_reply-exp](https://cloud.githubusercontent.com/assets/24651120/23860606/ba773af0-0807-11e7-965b-655b2033ecb2.jpg)
![vzkazy_reply](https://cloud.githubusercontent.com/assets/24651120/23860608/ba7ac008-0807-11e7-944a-7782649acb5a.jpg)

**Comment by ra100** [comment]
Este jedna poznamka, stale sa tam spomina Zmazat, ale mazat sa nic nebude. Hlavne z dovodu, ze ak je nieco priamo z feedu twitter alebo pod. Tak by sa ten post zakazdym updatom aj tak pridal. Takze moznost mazania postov v systeme vobec nie je.

**Comment by Evzenecek** [comment]
Počítám s tím, že smazat by tedy měly jít pouze rozhlasové příspěvky.

**Comment by ra100** [comment]
For review.

**Comment by Evzenecek** [comment]
Jen koukám, že klik na "Login" a "New post" asi vyvolává stejný popup se stejným textem...
Správně mají být 2: Login ti vyvolá možnost loginu cos chtěl. New post ti říká, že nemůžeš přidat new post, protože se musíš lognout.

**Comment by Evzenecek** [comment]
Další připomínky, převážně od Aleše:

1.	hláška u špatně zadaného hesla
Pokud se uživatel loguje již zaregistrovaným uživatelským účtem a vyplní špatné heslo, vypisuje to nějakou systémovou hlášku. 
Ideální by bylo, pokud bychom byli schopní rozlišovat neexistující login a špatně zadané heslo – tomu pak přizpůsobit chybovou hlášku.
Pokud to nelze, dejme standardní „Špatný email nebo heslo“.

2.	průhledná linka mezi šedou menu lištou a popupem „login/new post“
Nyní je průhledná a prosvítá tam obsah pod popupem. Aleš prosí, zda můžeš udělat bílou, aby tam nic neprosvítalo.

3.	šedé zóny v pop-upu „login“ pod jednotlivými sociálními sítěmi
Viz screen. Oproti Alešovu grafickému návrhu jsou v loginboxu u jednotlivých sociálních sítí šedý rámečky, v každym prohlížeči navíc jinou barvou. Asi ti to tam zbylo jako nějakej relikt, tak jestli se toho můžeš zbavit…

4.	sjednotit barvy podle E7 palety
Mohl by jsi použité barvy upravit podle nejbližší barvy v Alešově paletě pro E7, ať je to jednotné s novým Drupalovým vizuálem? Již je tu nasdílena, viz výše.

5.	texty v šedé menu liště nemají být tučně
Podle Alešovy grafiky to má být standardním řezem.

6.	nyní lze odpovídat na příspěvek i bez přihlášení a až těsně před odesláním to vyhodí chybu
Správně má být: pokud nejsi přihlášen a klikneš na „reagovat“, měl by se ti otevřít pop-up „new post“ – nejprve se musíte přihlásit.

7.	chybí stromeček znázorňující návaznost odpovědí
Je možné implementovat grafický strom pro hierarchii postovaných odpovědí, jako je v Alešových podkladech?

8.	na konci framu by měl být šedivý gradient
Počítáš s tím, že po uzavření shoutboxu do framu bude přítomný Alešův šedý gradient, co má v pdkladech? Nebo to bude až na kluky z provozu u nás?

9.	okna „login“ a „new post“ by měla mít křížek vpravo nahoře, aby mohla být uživatelem zavřena.

10.	nová ikonka pro rozhlasový účet, viz Alešova ikonka
Aleš vytvořil novou ikonku pro rozhlasový účet do popupů „login“ a případně „new post“, je třeba nahradit.

11.	buton „načíst více“ není podle Alešovy grafiky
Spodní button „načíst další“ není dle Alešovy grafiky, prosí o upravení.

12.	responzivita – mobilní shoutbox by neměl jít rozšířit
A jen ověření: počítáme s tím, že mobilní verze shoutboxu nebude rozšiřitelná, a tudíž nebude přítomen button vpravo nahoře?

![2_m](https://cloud.githubusercontent.com/assets/24651120/24108223/4fc3a78a-0d8d-11e7-8762-bff0894eaedf.jpg)

<img width="805" alt="screen shot 2017-03-20 at 10 36 11" src="https://cloud.githubusercontent.com/assets/24651120/24108224/4fc325f8-0d8d-11e7-82df-9bd0077be6c7.png">

**Comment by Evzenecek** [comment]
[btn_cro_sprite.svg.zip](https://github.com/ra100/shoutbox-widget/files/855547/btn_cro_sprite.svg.zip)

**Comment by Evzenecek** [comment]
Koukám, že z widgetu (pokud jsem lognutý jako admin) se nedá schvalovat příspěvky čekající na schválení - jdou jen smazat a zakázat.

**Comment by ra100** [comment]
Pre zobrazenie, schvalenie a pod. je dost pravidiel, co sa kedy moze stat s prispevkom a este je rozdiel, ci je to cez shoutbox alebo zo socnetu.
Ako som uz pisal, tak pre socnetove plati, ze sa nemozu zmazat, daju sa len skryt. Zmazat sa daju len tie, co niekto napisal cez shoutbox.

| stav | | | akcia | | | |
|------|-|-|-|---------|-|-|
| novy | schvaleny | zobrazeny | zobrazit | skryt | schvalit | zakazat |
| A      | N               | N               | *            |          |             | *         |
| A      | N               | N               | *            |          |             | *         |
| A      | N               | N               | *            |          |             | *         |

**Comment by ra100** [comment]
tie co som nezaskrtol ako hotove

* 7 - stromecek - nebude, nevidim ziaden jednoduchy alebo sebejednoduchsi sposob ako to vyrobit
* 9 - a preco to nie je nikde v designe? Nestaci, ked sa kliknutim na new message zas okno zavrie? Button funguje ako "toggle", nie len "open"
* 12 - vyskusaj si to na mobile, tam sa shoutbox tie moze expandovat, ale max do sirky obrazovky

> Koukám, že z widgetu (pokud jsem lognutý jako admin) se nedá schvalovat příspěvky čekající na schválení - jdou jen smazat a zakázat.

 zakazat skryje prispevok, kedze nepublikovany prispevok je uz skryty, tak nedava zmysel, aby tam bol este button skryt, pravidla viz vyse

> Mazání příspěvku přes toto rozhraní také nefunguje - nic se neděje.

* asi fixed, aky browser, os?

> Skrytý příspěvek jde nyní pouze zviditelnit - měl by jít i smazat.

* fixed, viz vyse

**Comment by Evzenecek** [comment]
Jsem lognutý jako AdministraThor a stále mi to nebere v interface žádné akce - nemůžu mazat ani sschvalovat ani skrývat.
MacOS, Chrome.

Ohledně stromečku: napadá tě tedy nějaké alternativní řešení, jak by šlo podobně symbolizovat hierarchii příspěvků?

**Comment by ra100** [comment]
* Akcie z interface, pokracovanie pls v #39, mozes otvorit konzolu CMD+I, ci to nevyhodi nejaku chybu, ked kliknes na skryt a pod.
* stromecek, slo by spravit nieco taketo
![image4144](https://cloud.githubusercontent.com/assets/3185410/24368963/c5eef672-1322-11e7-9b82-e5eb5e014e03.png)

**Comment by Evzenecek** [comment]
Stromeček: OK, zkus to tedy takto, lepší než nic. Jen prosím použij barvu z Alešovy palety.

Jinak jsme ještě koukali, že scrollbar zasahuje přímo do prostoru Shoutboxu, místo aby byla vedle něho. Můžeš s tím něco provést?
Dík.

**Comment by ra100** [comment]
Scrollbar inak ako "z vnutornej" strany byt nemoze, a da sa stylovat len teoreticky, stylovanie scrollbaru nie je W3C standard a ak to niekde funguje, tak to je len dobra vola browseru.

**Comment by ra100** [comment]
At barvy, paleta je relativne siroka, pomohlo by vediet, ktora ta seda ma byt vlastne kde. anyway, farby z palety tam su.

**Comment by Evzenecek** [comment]
Dík.
Můžeš teda nějak docvaknout ten stromeček?

**Comment by ra100** [comment]
Stromecek je tam. Snad je to uz vsetko z tejto sekcie.
