### ISSUE TITLE
Nová grafika - celý koncept

### ISSUE THREAD

**Issue by Evzenecek** [ra100/shoutbox-widget#37]
Požadované podklady + úpravy.

Nějaká teorie:
Ikony Odpovědi, retweetů a likes ze sociálních sítí zatím nechceme zobrazovat, chceme tam mít pouze odkaz na vlastní URL příspěvku na sociální síti a naše odpovědi přes rozhlasový účet, viz Alešovo řešení (ikona + počet).
Pokud je to nula, tak jen šipka. Pokud je to 1 a více, zobrazujeme i číslo.
Klik na šipku otevírá okno "Odpovědět".

Defaultně zobrazujeme 2 nejnovější odpovědi.

![1_d](https://cloud.githubusercontent.com/assets/24651120/23803053/967b0cd4-05b5-11e7-9cd1-2a59169d6f24.jpg)
![1_m](https://cloud.githubusercontent.com/assets/24651120/23803055/96a12bee-05b5-11e7-86ac-e2f333b8b358.jpg)
![2_m](https://cloud.githubusercontent.com/assets/24651120/23803056/96a3424e-05b5-11e7-8e83-62d7f85612ef.jpg)
![3_m](https://cloud.githubusercontent.com/assets/24651120/23803058/96a88196-05b5-11e7-8f70-a58e51f9afeb.jpg)
![4_m](https://cloud.githubusercontent.com/assets/24651120/23803054/96a137e2-05b5-11e7-90ab-f4d3ddcf35e1.jpg)
![5_m](https://cloud.githubusercontent.com/assets/24651120/23803057/96a650e2-05b5-11e7-9d7f-c43a8157fc79.jpg)
![6_m](https://cloud.githubusercontent.com/assets/24651120/23803059/96bdff58-05b5-11e7-8234-a185400c556e.jpg)

**Comment by ra100** [comment]
Related to #36 
closing
