### ISSUE TITLE
Admin actions not working on Chrome (OSX)

### ISSUE THREAD

**Issue by ra100** [ra100/shoutbox-widget#39]

**Comment by Evzenecek** [comment]
Chrome console errors:

shoutbox.rozhlas.cz/:1 XMLHttpRequest cannot load https://shoutbox.rozhlas.cz/csrfToken. The 'Access-Control-Allow-Origin' header contains the invalid value ''. Origin 'http://shoutbox.rozhlas.cz' is therefore not allowed access.

client.js:625 Uncaught (in promise) Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
    at f.crossDomainError (client.js:625)
    at XMLHttpRequest.e.onreadystatechange (client.js:733)
f.crossDomainError @ client.js:625
e.onreadystatechange @ client.js:733
sails.io.js:422 

  |>    Now connected to Sails.
\___/   For help, see: http://bit.ly/1DmTvgK
        (using sails.io.js node SDK @v1.1.5)

**Comment by ra100** [comment]
To je presne ono, musis pouzivat https, lebo inak je to insecure a nedovoli ti nic robit

**Comment by Evzenecek** [comment]
Máš pravdu, s https to funguje.
Dalo by se to nějak potunit, aby to bylo blbuvzdorný? Třeba že to bude vždy přesměrovávat na https?
A jak to bude s tím, že celý Drupal web ještě není v https? Znamená to, že admini nebudou moct přes widget zatím nic dělat?

**Comment by ra100** [comment]
Wait a second, bez toho aby web bezal na https to asi nepojde. S https som pocital od zaciatku, s tym, ze inak ako https uz web fungovat nebude.

**Comment by Evzenecek** [comment]
Tak dobrý - prej https poběží do tejdne, takže na 99% poběží v době migrace Wavu.
