### ISSUE TITLE
Bug: do moderování jsou zahrnuté i příspěvky ze sociálních sítí

### ISSUE THREAD

**Issue by Evzenecek** [ra100/shoutbox-widget#41]
Do moderování by měly být zahrnuté jen příspěvky uživatelů skrze rozhlasový účet.
Nyní tam jsou zahrnuty i příspěvky ze sociálních sítí, což nedává smysl.

**Comment by ra100** [comment]
Preco by to tam nemalo byt, ta moznost, napr. v pripade, ze z 2 zdrojov tam bude rovnaky post, nie je dobre mat moznost skryt ho? Mat moznost moderovania aj tych prispevkov? Napr. v sledovani hashtagu z twitteru.

**Comment by Evzenecek** [comment]
Určitě ponechat možnost moderovat příspěvky, ale nikoliv je nutně všechny schvalovat.
Feedy účtů ze sociálních sítí neschvalovat, z hastagů to prosím dej volitelně... Myslím, že se jim to nebude chtít moderovat.

**Comment by ra100** [comment]
To bude problem, nutnost moderacie sa nastavuje pre cely stream, nie pre jednotlive feedy.

**Comment by Evzenecek** [comment]
Tak to je problém...
Nedovedu si představit, že Wave bude schvalovat každý svůj příspěvek z FB a Twitter, nedává to smysl.
Je třeba to upravit.

**Comment by ra100** [comment]
backend, riesit sa to bude tu https://github.com/ra100/sails-social-feed/issues/26
moznost moderacie tam stale ostava, ale pre kazdy feed sa da nastavit, ci sa maju zobrazovat posty alebo nie automaticky.
