### ISSUE TITLE
Stromeček - "zobrazit starší reakce"

### ISSUE THREAD

**Issue by Evzenecek** [ra100/shoutbox-widget#44]
Nějak blbne zobrazování reakcí na příspěvek, pokud jich je víc než 3.

Správně má být, že se zobrazují 2 nejnovější a starší jsou schované pod buttonem "zobrazit starší reakce".
Nyní, když má příspěvek 3 reakce, tak jsou viditelné 2 nejstarší a ta jedna nejnovější je skrytá.

Po kliku na "zobrazit starší reakce" se navíc řazení znovu změní a nyní je správně: dole nejnovější reakce, nahoře nejstarší.

**Comment by ra100** [comment]
Ake by malo byt spravanie v pripade, ze tych reakcii tam bude 100? Rozbalit vsetkych 100, alebo postupne rozklikavat "zobrazi starsi" napr. po 10?
