### ISSUE TITLE
button "Zobrazit starší"

### ISSUE THREAD

**Issue by Evzenecek** [ra100/shoutbox-widget#45]
Vidím trochu problém s tím šedým gradientem, co je nad buttonem "zobrazit starší" a zakrývá aktivní plochu - když jsou pod gradientem viditelné odkazy nebo buttony, nelze na ně kliknout.

Co s tím? Ideální by bylo, aby se i přes gradient dalo kliknout.
Pokud by to byl problém, tak aspoň dejme, že klik do gradientu se bude brát jako klik na button "zobrazit starší"...
Dík!

**Comment by ra100** [comment]
Gradient musi byt nad textom, cize ked na to kliknes, tak nemozes zachytit ten klik pod gradientom.

**Comment by Evzenecek** [comment]
Ok. A ta myšlenka, že gradient bude stejný odkaz, jako celý button?

**Comment by ra100** [comment]
Ok, to nebude problem.
