### ISSUE TITLE
Špatné hlášky při pokusu o login do admin UI

### ISSUE THREAD

**Issue by Evzenecek** [ra100/shoutbox-widget#47]
Špatné heslo nebo neexistující login = "Nezadali jste heslo"
Nezadané heslo = "Chyba při přihlášení"

Můžeme lépe?
Neexistující login = tento login neexistuje
Špatné heslo = špatné heslo
Nezadané heslo = nezadáno heslo

**Comment by ra100** [comment]
Move to backend: https://github.com/ra100/sails-social-feed/issues/27
