### ISSUE TITLE
Špatné vykreslování šířky shoutboxu při skrytém scrolleru

### ISSUE THREAD

**Issue by Evzenecek** [ra100/shoutbox-widget#49]
Aleš má na MacOS nastaveno, že scrollery jsou nativně skryté a jsou vidět až po začátku scrollování.
Při tomto nastavení se ale vždy minimálně v prohlížečích Safari + Firefox + Chrome posty v shoutboxu vykreslí širší a následně zviditelněný scroller je pak přes ně.
Ukázka viz screen.

![screen shot 2017-05-18 at 13 29 30](https://cloud.githubusercontent.com/assets/24651120/26200396/38ffcf3c-3bce-11e7-8758-3eb5a5678a00.png)

**Comment by ra100** [comment]
Check it plz

**Comment by Evzenecek** [comment]
Pořád stejné, nic se neprojevilo.

**Comment by ra100** [comment]
refresh now

**Comment by Evzenecek** [comment]
Teď je v Safari a Chrome scroller natvrdo a vykreslování je správné, v Mozille nic.
A Aleš říká, že to není nativní sscroller, ale nějakej jinej.

**Comment by ra100** [comment]
Ak to v moz nebude ani teraz, tak to tam uz nebude, lebo Mozilla nepodporuje uplne zmenu scrollbaru.
A scroller of course nie je nativny, inak by sa tak uplne nezobrazil.

**Comment by Evzenecek** [comment]
Ne, v Mozille pořád nic.
Jestli jiná možnost opravy než implementace scrollbaru natvrdo není, tak asi ok mno...

**Comment by ra100** [comment]
Momentalne ina moznost ako je to teraz, nie je. Toto je len stylovanie scrollbaru. Ak chces vlastnu implementaciu scrollbaru, tak poprosim graficky desing, ako sa to ma spravat a 1-2 vikendy.
