### ISSUE TITLE
Po lognutí se nerefreshne shoutbox

### ISSUE THREAD

**Issue by Evzenecek** [ra100/shoutbox-widget#51]
Po provedení loginu skrze rozhlasový acc se nic nestane a musí se ručně refreshnout stránka, aby se provedly změny a uživatel byl zalogovaný. Nezobrazí se žádná výstražná hláška, v url je HTTPS.
**Děje se to vždy tehdy, když se ručně odhlásím a následně se chci znovu přihlásit.** Možná i jindy po automatickém odhlášení, nevím.

Chrome, MacOS. Láďovi to prý ale také dělá i na Win.

**Comment by Evzenecek** [comment]
Dělá to i při logování přes FB.

**Comment by ra100** [comment]
Uz by to malo byt fixnute, spravil som viac veci, jednou z nich je, ze autoclose popupu ma 3s timout, tak dufam, ze to uz bude vsetko OK.
