### ISSUE TITLE
Příspěvky uživatelů na stránce na FB feedu

### ISSUE THREAD

**Issue by Evzenecek** [ra100/shoutbox-widget#52]
V shoutboxu se zobrazují některé příspěvky uživatelů z FB feedu.
Ideálním cílem je, aby v nastavení byla možnost u feedu "Zobrazovat i příspěvky fanoušků na stránce" a admin to mohl u každého feedu zapnout/vypnout.

**Comment by ra100** [comment]
toto je FB randomness, aspon tak to vidim, z toho co ide v datach

**Comment by ra100** [comment]
Tak toto by uz malo byt fixnute
