### ISSUE TITLE
Nelze vložit obrázek

### ISSUE THREAD

**Issue by Evzenecek** [ra100/shoutbox-widget#53]
Do shoutboxu nelze skrze widget vložit obrázek - výstražná hláška a vkládaný obrázek viz příloha.
Chrome, MacOS + Win

+ návrh na feature: obrázek by mohl jít odeslat i bez textu v příspěvku (dnes musí nějaký text v příspěvku být....)

![copy of photo collage untitled design 1](https://user-images.githubusercontent.com/24651120/27800413-92d0bbba-6019-11e7-91be-f98e8a812860.png)

![image](https://user-images.githubusercontent.com/24651120/27800397-87b36782-6019-11e7-9cfc-75fb676a07af.png)

**Comment by Evzenecek** [comment]
Tak už nejde vložit dokonce ani textový příspěvek, je o rozbitý :-(

**Comment by ra100** [comment]
tohto bugu som sa este nedotokol, takze komplet, co sa ako posiela ma este caka

**Comment by ra100** [comment]
obrazky sa sa daju uz posielat bez textu a text bez obrazku, pripadne oboje naraz a konecne by to naozaj aj malo posielat
