### ISSUE TITLE
Náhled FB galerie (nejen) z FB feedu

### ISSUE THREAD

**Issue by Evzenecek** [ra100/shoutbox-widget#54]
Můžeme vytvořit dynamický náhled? Ve stylu třeba 3 obrázků a pod tím odkaz k zobrazení dalších přímo na FB?
Bruštík hlásil, že pokud je galerie sdílená na FB, tak se v shoutboxu vykreslí nějak hrozivě a zobrazí to všechny fotky.... nebo prý někdy dá každou jednu fotku samostatně jako jeden post... Můžeš zkontrolovat?
Navíc: galerie se někdy zobrazuje, jako by jí vložila osoba a ne Radio Wave. 

Jinak potřebuješ na to grafický návrh, nebo můžeš použít nějaký default, jak to třeba dělá FB?

**Comment by ra100** [comment]
Je to teraz uz lepsie?

**Comment by ra100** [comment]
chce to este kontrolu od niekoho ineho ako som ja, ale myslim, ze to uz je tak ako to ma byt
+ poslednych par dni sa zobrazuju v streame posty z twitteru aj FB bez schavalenia, tak ako by to malo byt. Ak by tam bolo stale nieco zle, tak zas tuto issue otvorim
