### ISSUE TITLE
Nefunkční nastavení streamu

### ISSUE THREAD

**Issue by Evzenecek** [ra100/shoutbox-widget#58]
V administraci se nejde dostat do nastavení Streamu, kde by měly být zobrazené feedy... Hlásí to bug nebo se vůbec nic nenačte...

Btw., v tomto nastavení se pak bude dást nastavit, jestli mají být feedy moderované, tzn. i  od Rozhlasového účtu?

**Comment by Evzenecek** [comment]
Počítám, že v tomto nastavení pak půjdou vidět příspěvky a půjdou také editovat odtud, nejenom z user interface.

**Comment by ra100** [comment]
Prosim o reprodukciu krokov, jak ze sa neda dostat do nastavenia streamu? Pod akym userom, aky stream (teda je tam len jeden, takze tam je odpoved jasna).
![66b12c9f-b894-4411-ba5d-73f1d238c0fc](https://user-images.githubusercontent.com/3185410/29807714-73d544e4-8c95-11e7-994a-584c89861ac3.png)

**Comment by Evzenecek** [comment]
Nejde mi to přes HTTPS ani HTTP.
Nejede to pod mým Rozhlasovým acc Honzinátor.
Když se lognu na acc admin, tak mi to už jde. Je to divný, protože Honzinátor má taky roli admin... Možná yb to mohlo být tím, že nemám group wave...

![image](https://user-images.githubusercontent.com/24651120/29809193-82a2bf96-8c9b-11e7-8a37-8965ca5490ce.png)

**Comment by ra100** [comment]
No, tak to vyzera ze byt len admin nestacit, ale musis mat aj priradene groupy
