### ISSUE TITLE
Špatné loadování shoutboxu

### ISSUE THREAD

**Issue by Evzenecek** [ra100/shoutbox-widget#59]
Při každém druhém refreshi UI shoutboxu se nevykreslí celý, ale jen horní část a žádné příspěvky.
Občas se zase ve feedu nezobrazují neschválené příspěvky čekající na moderování. Docela často.

MacOS, Chrome + Safari

**Comment by ra100** [comment]
Prihlaseny, neprihlaseny, je to jedno?
Prispevky odkial? Od usera? Z FB, TW, Instagramu?
Prosim o pouzitelne bugreporty.

**Comment by Evzenecek** [comment]
Děje se mi to zas pod acc Honzinátor, na acc admin jsem to teď nezaznamenal.

Taky jsem si všiml, že i když má Honzinátor roli admin, nezobrazují se jeho příspěvky jako adminské a spadají pod moderování. Adminství v UI se děje dle group Wave, co je přiřazená tomuto streamu?
Dík.

**Comment by Evzenecek** [comment]
Nový poznatek: Když je user admin v group "admin" i "Wave", neděje se to a je to každé načtení v pohodě. Pokud mu seberu "Wave" a nechám jen "admin", zase se to děje.

**Comment by ra100** [comment]
Group admin by tam ani nemala byt, nema vyznam. Ak si len editor a nie si v groupe, co vlastni stream, tak nemas prava editovat stream.
