### ISSUE TITLE
Nelze autentifikovat FB feed

### ISSUE THREAD

**Issue by Evzenecek** [ra100/shoutbox-widget#61]
Stream založen, feedy taky. Jen mám problém s autentizací FB feedu. Jsem na FB lognutej na sebe, mám roli Editora na FB Wavu, klikám na autentifikovat a nefachá, stále neautentifikováno. Jedná se o stream Wave_ostrý.
Jsem lognutej přes acc admin.
Koukneš na to pls? Taky máš stále na Wavu editora.

**Comment by ra100** [comment]
postup:

1. prihlasit sa cez widget FB uctom, ktory na pristup/prava k page
2. pridelit tomuto userovit editora + groupu
3. tymto FB userom otvorit administraciu
4. otvorit feed
5. authorize

- ak tato FB page pouzita v inom feede, tak to asi nebude fungovat, testovaci feed sa bude musiet zmazat/zmenit na inu fb page

**Comment by Evzenecek** [comment]
Dělal jsem to podle návodu a stále nejde autentifikovat.
Smazal jsem autentifikovaný feed v testovacím streamu, založil nový FB Wave feed v ostrém a pak i znovu v testovacím streamu a ani jeden nejde autentifikovat.

A btw, co autentifikace Twitteru, to se dělá jak? Musím to mít taky nasdílené nebo být přihlášenej jako správce?

**Comment by ra100** [comment]
Tak oprava, nemusis byt prihlaseny pod userom, ktory je FB ucet, staci ked si admin/editor, das authenticate, presmeruje ta na FB, prihlasis sa (FB uctom, ktory je, myslim, aspon moderator stranky), potvrdis, done.

**Comment by ra100** [comment]
Twitter podobne, len s tym rozdielom, ze sa prihlasis akymkolvek twitter uctom a potvrdis, ze davas shoutboxu pristup.

**Comment by Evzenecek** [comment]
Vidím, že ty už jsi to autentifikoval, ale mně to fakt nejde.
Nešlo mi to u Wavu, nejde mi to ani těď u mojí vlastní FB stránky, co jsem dal do testovacího streamu.
Dělám to přes acc admin nebo Honzinátor, po každém subbmitu "Autentificate" to hlásí červeně "No access - authenticate now"...
Měli bychom to vychytat, ať to nemusíš dělat ty.

**Comment by ra100** [comment]
Na to sa budeme musiet seriozne pozriet, co to pise v logoch, aky je problem. Ocividne to sam nedokazem otestovat, iba ak by som si vyrobil/vyhrabal nejaky druhy FB ucet :)

**Comment by ra100** [comment]
Uz viem, preco to nefunguje, lebo nie si Admin tejto Fb appky, ked som si svoj ucet pridal ako admina, tak to zacalo fungovat. Ale aby to fungovalo aj pre neadminov, tak treba `manage_page` permissions, na co zas treba poslat screencast na review. Co som spravil a cakam na odpoved. Ak to nepojde (neschvalia), tak kazdy, kto bude potrebovat authentifikovat feed, bude musiet byt pridany ako admin do appky na developer portali.

**Comment by Evzenecek** [comment]
Tak mě přidej jako admina, mám acc na Facebook developers, už jsem tam něco hašil.
Díks. Btw, Instagram ještě neschválili?

**Comment by ra100** [comment]
poslal som ti request, na developer facebook
instagram zatial pending
facebook zatial declined, nieco s test accountami
