### ISSUE TITLE
Ve streamu se špatně vykreslují události FB feedu

### ISSUE THREAD

**Issue by Evzenecek** [ra100/shoutbox-widget#62]
Součástí FB feedu jsou události, které stránka vytvoří.
Ty jsou ale špatně vykreslené - zobrazuje se celý text události, ať je jakkoliv dlouhý. Co s tím můžeme dělat? Vyhodit to z feedu, nebo jen nastavit maximální délku znaků?

Událost na FB:
https://www.facebook.com/events/235266573648520/?acontext=%7B%22source%22%3A5%2C%22page_id_source%22%3A124596689571%2C%22action_history%22%3A[%7B%22surface%22%3A%22page%22%2C%22mechanism%22%3A%22main_list%22%2C%22extra_data%22%3A%22%7B%5C%22page_id%5C%22%3A124596689571%2C%5C%22tour_id%5C%22%3Anull%7D%22%7D]%2C%22has_source%22%3Atrue%7D
Obrázek z SB v příloze.
![image](https://user-images.githubusercontent.com/24651120/29863482-21d93638-8d70-11e7-90ac-19fe13b5015d.png)

**Comment by ra100** [comment]
Ako to vyriesit? Trunc po napr. 300 znakoch a tlacitko "expand"? V datach uplne neviem, ze to je event, tvari sa to ako normalny status.

**Comment by Evzenecek** [comment]
Tak můžeme po 200 znacích a tlačítko "Zobrazit celé"?

**Comment by Evzenecek** [comment]
Tohle bude taky vidět až po přehrání naší verze Shoutboxu tvojí novou?
Uděláš pls ten zásah, ať může Marek přehrát?
Dík!

**Comment by ra100** [comment]
Je to tam, len treba pouzit novy skript.
