### ISSUE TITLE
Příliš dlouhý nick usera přesahuje do symbolu R

### ISSUE THREAD

**Issue by Evzenecek** [ra100/shoutbox-widget#63]
Pokud je jméno usera příliš dlouhé, přesahuje do symbolu R, viz screen.
Můžeš to nějak nastylovat, ať se to zalomí? Díks!

![image](https://user-images.githubusercontent.com/24651120/29875643-f07b1590-8d9a-11e7-9868-2b349463d9c4.png)

**Comment by ra100** [comment]
nejak sa to zalomit moze, to ano, alebo bude to hnusne

**Comment by Evzenecek** [comment]
Udělal jsi s tím tedy něco, nebo chceš něco ode mě, nebo na to chceš kašlat a jen dáme třeba limit na délku nicku?

**Comment by Evzenecek** [comment]
Už to vidím, sry, měl jsem to nacachované.
Projevilo se, pěkný.

**Comment by Evzenecek** [comment]
Na tvym widgetu se to projevilo, ale ve widgetu, co mají kluci na http://wave.drupal.cro.cz/ nikoliv. Musí oni updatnout verzi, nebo to je zas jen cache?

**Comment by ra100** [comment]
musia spravit novy build alebo stiahnut nove .js subory
