### ISSUE TITLE
Prefixovane CSSka

### ISSUE THREAD

**Issue by Posp** [ra100/shoutbox-widget#66]
Současná verze App.scss může způsobit kolizi se zbytkem stránky, ať už stylováním základních tagů (body, a), tak relativně obecně nazvanými třídami (.error, .icon).

Navrhuji všechny deklarace limitovat na ID=shoutbox. Pošlu pullrequest.

**Comment by Posp** [comment]
Pullrequest zde https://github.com/ra100/shoutbox-widget/pull/67

**Comment by ra100** [comment]
Actually, mozno lepsie resenie bude pouzit @scoped styly v shoutboxe, to si potom appka oprefixuje vsetko sama.

**Comment by Posp** [comment]
To nevím co je, ale pokud to bude mít podobný výsledek tak klidně :)
Jo a bylo by možné parametrizovat url v `background-image: url('/static.../);`? Můžu na to kdyžtak založit vedlejší issue

**Comment by Evzenecek** [comment]
Jen pozor při updatu verze Shoutboxu na straně ČRo - je tam Markův hack CSSek, nesmí se přemazat. Viz https://github.com/ra100/shoutbox-widget/issues/68.

**Comment by Posp** [comment]
Hmmm... koukám, že jak Marek, tak Pepa Mareška upravují ten výstupní CSS soubor... Tak to asi nemá cenu toto issue vůbec řešit, protože bych musel z commitů vytáhnout všechny změny, přenést je do scssu a pak to sem vše napushovat. A to se mi nechce :D

**Comment by Evzenecek** [comment]
Asi vyřešeno a můžeme zavřít... Vyřešeno dočasně úpravou kaskád u nás na produ, dál řeším v #68.
