### ISSUE TITLE
V UI widgetu nelze editovat profil

### ISSUE THREAD

**Issue by Evzenecek** [ra100/shoutbox-widget#69]
Nelze editovat uživatelský profil v UI widgetu - stále hlásí chybu "sezení vypršelo". Např. u pokusu změnit přezdívku.

**Comment by ra100** [comment]
No, vidim chybu, call na https://shoutbox.rozhlas.cz/csrfToken vracia prazdny token

**Comment by ra100** [comment]
Fixed v konfiguracii, Cross Origin, musi tam byt explicitne meno domeny, nie wildcard

**Comment by Evzenecek** [comment]
Díky, funguje.
