### ISSUE TITLE
User info edit

### ISSUE THREAD

**Issue by ra100** [ra100/shoutbox-widget#8]
User should be able to edit her account info

* change password
* change name
* upload profile picture

**Comment by Evzenecek** [comment]
+ add email (pokud se lognul sociální sítí a nemáme ho)

**Comment by Evzenecek** [comment]
+ související bug: když si do svého účtu vytvořeného lognutím skrze Facebook (10208995820112072_facebook) vložím email a nastavím heslo, pak se těmito údaji stejně nemůžu lognout do shoutbox widgetu... Hlásí to nějaký univerzální bug, asi špatné heslo nebo neexistující user.
